name: Scala CI
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-actions-10"
  EB_APPLICATION_NAME       : "Scala"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Echo out a GitHub Actions Secret to the logs
      run: echo ${{ secrets.MY_SECRET_KEY }}

    - name: "Trick to echo GitHub Actions Secret:"
      run: echo ${{secrets.MY_SECRET_KEY}} | sed 's/./& /g' 
